#!/bin/sh /etc/rc.common
# (C) 2008 openwrt.org

START=50

start() {
	if [ -x /lib/cs75xx/setup_cs_wfo_mode.sh ]; then
		pci0=`get_pci_dev.sh | awk '{print $1}'`
		[ pci0 -ge 0 ] && /lib/cs75xx/setup_cs_wfo_mode.sh 0 1
		pci1=`get_pci_dev.sh | awk '{print $2}'`
		[ pci1 -ge 0 ] && /lib/cs75xx/setup_cs_wfo_mode.sh 1 1
		pci2=`get_pci_dev.sh | awk '{print $3}'`
		[ pci2 -ge 0 ] && /lib/cs75xx/setup_cs_wfo_mode.sh 2 1
	fi
}

stop() {
	ifconfig wlan0 down
}
