#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=30

start() {
	. /lib/cs75xx/wifi.sh
	
	config_load wifi
	
	DEV_ID=0
	for DEV_TYPE in `get_pci_dev.sh`; do
		if [ $DEV_TYPE -ge 0 ]; then
			local IF_NAME
			local DEV_NAME
			local HTMODE
			local CHANNEL

			setup_cs_wfo_mode $DEV_TYPE $DEV_ID 1
			sleep 2
			if [ $? -eq 0 ]; then
				DEV_NAME="wifi$DEV_ID"

				config_get IF_NAME $DEV_NAME ifname
				config_get MODE $DEV_NAME mode master
				config_get HTMODE $DEV_NAME htmode 11ACVHT80
				config_get CHANNEL $DEV_NAME channel 48

				if [ -n $IF_NAME ]; then
					case "$MODE" in
						"master")
							wlanconfig "$IF_NAME" create wlandev "$DEV_NAME" wlanmode ap
						;;
						"client")
							wlanconfig "$IF_NAME" create wlandev "$DEV_NAME" 
						;;
					esac	

				fi
   				iwpriv "$IF_NAME" mode $HTMODE
				iwconfig "$IF_NAME" channel $CHANNEL
			fi

			DEV_ID=`expr $DEV_ID + 1`
		fi
	done

	echo 1 > /proc/irq/65/smp_affinity
	echo 2 > /proc/irq/70/smp_affinity
}

stop() {
	none;
}

restart() {
	stop
	start
}
