#!/bin/sh /etc/rc.common 
# (C) 2008 openwrt.org

START=90

config_ap() {
	local	MODE
	local	VAP_NAME
	local	ESSID
	local	CHANNEL
	local	WDS
	local	SHORTGI
	local	LDPC

	config_get VAP_NAME $1 vapname
	config_get ESSID $1 essid
	config_get WDS $1 wds
	config_get SHORTGI $1 shortgi
	config_get LDPC $1 ldpc

	if [ -z $VAP_NAME ] || [ -z $ESSID ] ; then
		return	1
	fi

	[ -z $WDS ] && WDS=1
	[ -z $SHORTGI ] && SHORTGI=1
	[ -z $LDPC ] && LDPC=1
	
	sleep 1
	iwpriv "$VAP_NAME" wds $WDS
	iwconfig "$VAP_NAME" essid $ESSID
	iwpriv "$VAP_NAME" shortgi $SHORTGI
	iwpriv "$VAP_NAME" ldpc $LDPC 
	ifconfig "$VAP_NAME" up
}

disable_ap() {
	local	VAP_NAME

	config_get VAP_NAME $1 vapname

	if [ -z $VAP_NAME ] ; then
		return	1
	fi

	ifconfig "$VAP_NAME" down
}

start() {
	config_load ap

	config_foreach config_ap ap
}

stop() {
	config_load ap

	config_foreach diable_ap ap
}

