#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

mount_no_yaffs2() {
    echo "yaffs2 not ready yet; using ramdisk"
    ramoverlay
}

check_for_yaffs2() {
    check_skip || {
	yaffs2_ready || {
	    mount_no_yaffs2 && pi_mount_skip_next=true
	}
    }
}

boot_hook_add preinit_mount_root check_for_yaffs2

