#!/bin/sh

uci -q batch <<-EOF >/dev/null
        delete ucitrack.@miniupnpd[-1]
        add ucitrack miniupnpd
        set ucitrack.@miniupnpd[-1].init=miniupnpd
        commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
