#!/bin/sh /etc/rc.common

START=40
STOP=90

config_interface() {
	local 	ifname
	local	iftype
	local	proto
	local	ipaddr
	local	netmask
	local	bridge

	config_get ifname $1 'ifname'
	[ -z "$ifname" ] && return 0

	config_get iftype $1 'type' "none"

	case "$iftype" in
		"bridge")
			config_get bridge $1 bridge
			if [ -n "$bridge" ]; then
				IS_EXIST_BR=`brctl show | tail -n+2 | awk '{ if ($1 ~ $bridge) print 1  }' | tr -d '[[:space:]]'`
				if [ -n "$IS_EXIST_BR" ] ; then
					brctl addbr $bridge
				fi
		
				brctl addif $bridge $ifname 2> /dev/null
				ifconfig $ifname up
				ifconfig $bridge up
			fi
			ifname=$bridge	
			;;

		"loopback")
			ifconfig $ifname loopback
			;;

	esac

	config_get proto  $1 proto 
	case "$proto" in
		"static")
			config_get ipaddr $1 ipaddr
			config_get netmask $1 netmask
			if [ -n "$ipaddr" ] && [ -n "$netmask" ]; then
				ifconfig $ifname $ipaddr netmask $netmask	
			fi
			;;
		"dhcp")
			if [ -f /var/run/udhcpc.$ifname.pid ]; then
				cat /var/run/udhcpc.$ifname.pid | xargs kill 2> /dev/null
			fi
			udhcpc -t 0 -i $bridge -R -n -p /var/run/udhcpc.$ifname
			;;
	esac
}

start() {
	config_load network

	config_foreach config_interface interface
}

stop() {
	for ifname in `cat /proc/net/dev | tail -n+3 | awk '{print $1}' | sed 's/://'`; do
		if [ -f /var/run/udhcpc.$ifname.pid ]; then
			cat /var/run/udhcpc.$ifname.pid | xargs kill 2> /dev/null
		fi
		ifconfig "$ifname" 0.0.0.0 down 2> /dev/null
	done
}

restart() {
	stop
	start
}
