#!/bin/sh
#
uci -q batch <<-EOF >/dev/null
        delete ucitrack.@ftpsamba[-1]
        add ucitrack ftpsamba
        set ucitrack.@ftpsamba[-1].init=ftpsamba
        commit ucitrack
EOF
 
rm -f /tmp/luci-indexcache
exit 0
