#!/bin/sh
# Copyright (C) 2006-2010 OpenWrt.org
# Copyright (C) 2010 Vertical Communications

find_mount_yaffs2() {
	mkdir -p /tmp/overlay
    echo 'mount "$(find_mtd_part overlay)" /tmp/overlay -t yaffs2'
    mount "$(find_mtd_part overlay)" /tmp/overlay -t yaffs2
    mtd -qq unlock overlay
}

yaffs2_not_mounted() {
    if [ "$pi_yaffs2_mount_success" != "true" ]; then
	return 0
    else
	return 1
    fi
}

do_mount_yaffs2() {
    check_skip || {
	find_mount_yaffs2 && pi_yaffs2_mount_success=true
    }
}

boot_hook_add preinit_mount_root do_mount_yaffs2

